/*
	SDZGeoCode_ServiceExample.h
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
@interface SDZGeoCode_ServiceExample : NSObject {
}
-(void)run;
@end
		